name: Add Text to File and Commit

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

permissions:
  contents: write

jobs:
  update-records:
    runs-on: ubuntu-latest

    env:
      DATAFILE: yesterdays-records.txt

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Write random data to file
      run: python gen_records.py

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $DATAFILE
        git commit -m "add new daily records"
        git push
